version: '3.8'

networks:
  app_network:  # Red compartida entre los servicios
    driver: bridge

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    environment:
      SA_PASSWORD: "#password1"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    restart: unless-stopped
    networks:
      - app_network

volumes:
  sqlserver_data:
    driver: local
